library(forecast)
library(RMySQL)
library(zoo)
con <- dbConnect(MySQL(), user = 'root', password = 'root', host = 'localhost', dbname='test')
datas <- dbGetQuery(conn = con, statement = "select s.INTERVALLE + (s.JOUR - 1) * 288 as INTERVALLE, min(s.DATE), avg(s.DISPONIBLES) as DISPONIBLES  from station s where s.ID_STATION = '3003' and s.DATE between '2016-04-01' and '2016-04-07' group by s.JOUR, s.INTERVALLE order by s.ID;")
s3003 <- data.frame(datas)
inte <- seq(from = min(s3003$INTERVALLE), to = max(s3003$INTERVALLE))
inte <- data.frame(inte)
merge <- merge(inte, s3003, by.x=names(inte)[1], by.y="INTERVALLE", all.x = TRUE)
merge <- na.locf(merge)
s1 <- ts(data = merge$DISPONIBLES, start = min(merge$inte), end = max(merge$inte), frequency = 1)
plot(s1)
fit <- auto.arima(s1)
fcast <- forecast(fit)
plot(fcast)
grid()
fcast
fit.arima<-arima(s1, order=c(2,0,2))
fcast.arima <- forecast(fit.arima)
plot(fcast.arima)
fcast.arima <- forecast(fit.arima, h=50)
plot(fcast.arima)
